export interface Product {
  id: number;
  name: string;
  description: string;
  image: string;
  category: string;
  price: string;
  cardSize: "small" | "medium" | "large";
}

export const products: Product[] = [
  {
    id: 1,
    name: "Artisan Coffee Blend",
    description: "Premium single-origin coffee beans roasted to perfection. Rich, smooth flavor with hints of chocolate and caramel. Ethically sourced from small farms.",
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&h=400&fit=crop",
    category: "Food & Drink",
    price: "$24.99",
    cardSize: "large",
  },
  {
    id: 2,
    name: "Hand-poured Soy Candle",
    description: "Luxurious soy wax candle infused with essential oils. Clean burning for up to 60 hours. Perfect for creating a relaxing atmosphere.",
    image: "https://images.unsplash.com/photo-1602607434932-06b9e8566049?w=400&h=400&fit=crop",
    category: "Home",
    price: "$18.99",
    cardSize: "medium",
  },
  {
    id: 3,
    name: "Organic Honey Jar",
    description: "Raw, unfiltered honey from local bee farms. Rich in natural enzymes and antioxidants. Perfect for tea, baking, or enjoying straight.",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=400&fit=crop",
    category: "Food & Drink",
    price: "$15.99",
    cardSize: "small",
  },
  {
    id: 4,
    name: "Linen Throw Blanket",
    description: "Handwoven linen throw blanket in natural tones. Lightweight yet warm. Gets softer with every wash. Perfect for any room.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop",
    category: "Home",
    price: "$89.99",
    cardSize: "large",
  },
  {
    id: 5,
    name: "Ceramic Dinner Set",
    description: "Handcrafted ceramic dinner set for 4. Each piece features unique glaze patterns. Microwave and dishwasher safe. Elegant matte finish.",
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400&h=400&fit=crop",
    category: "Kitchen",
    price: "$149.99",
    cardSize: "medium",
  },
  {
    id: 6,
    name: "Bamboo Utensil Set",
    description: "Eco-friendly bamboo kitchen utensil set. Includes spatula, spoon, fork, and chopsticks. Naturally antibacterial and durable.",
    image: "https://images.unsplash.com/photo-1584990347449-a2d4f0a2c7a4?w=400&h=400&fit=crop",
    category: "Kitchen",
    price: "$22.99",
    cardSize: "small",
  },
  {
    id: 7,
    name: "Essential Oil Diffuser",
    description: "Ultrasonic essential oil diffuser with ambient lighting. Whisper-quiet operation. Automatically shuts off when water runs low.",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&h=400&fit=crop",
    category: "Home",
    price: "$45.99",
    cardSize: "medium",
  },
  {
    id: 8,
    name: "Handmade Soap Collection",
    description: "Set of 4 artisan soaps made with natural ingredients. Lavender, eucalyptus, citrus, and rose scents. Gentle on sensitive skin.",
    image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&h=400&fit=crop",
    category: "Bath & Body",
    price: "$28.99",
    cardSize: "small",
  },
  {
    id: 9,
    name: "Cotton Canvas Tote",
    description: "Durable cotton canvas tote bag with reinforced handles. Spacious interior with zippered pocket. Machine washable for easy care.",
    image: "https://images.unsplash.com/photo-1597484661643-2f5fef26aa4b?w=400&h=400&fit=crop",
    category: "Accessories",
    price: "$34.99",
    cardSize: "large",
  },
  {
    id: 10,
    name: "Succulent Plant Set",
    description: "Collection of 3 easy-care succulents in ceramic pots. Perfect for desks, shelves, or windowsills. Includes care instructions.",
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&h=400&fit=crop",
    category: "Garden",
    price: "$29.99",
    cardSize: "medium",
  },
  {
    id: 11,
    name: "Wooden Salad Bowl",
    description: "Hand-turned wooden salad bowl from sustainable acacia wood. Food-safe finish. Perfect size for family servings. Hand wash recommended.",
    image: "https://images.unsplash.com/photo-1592418171486-46ab1be9e231?w=400&h=400&fit=crop",
    category: "Kitchen",
    price: "$54.99",
    cardSize: "medium",
  },
  {
    id: 12,
    name: "Beeswax Food Wraps",
    description: "Set of 3 reusable beeswax food wraps. Eco-friendly alternative to plastic wrap. Washable and compostable. Various sizes included.",
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400&h=400&fit=crop",
    category: "Kitchen",
    price: "$19.99",
    cardSize: "small",
  },
  {
    id: 13,
    name: "Macrame Wall Hanging",
    description: "Handwoven macrame wall art made from natural cotton cord. Bohemian style for any room. Ready to hang with wooden dowel included.",
    image: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=400&h=400&fit=crop",
    category: "Home",
    price: "$67.99",
    cardSize: "large",
  },
  {
    id: 14,
    name: "Loose Leaf Tea Collection",
    description: "Premium loose leaf tea sampler with 6 varieties. Includes black, green, oolong, and herbal blends. Comes in decorative tin.",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=400&fit=crop",
    category: "Food & Drink",
    price: "$36.99",
    cardSize: "medium",
  },
  {
    id: 15,
    name: "Natural Bath Salts",
    description: "Luxurious bath salts infused with eucalyptus and magnesium. Soothes tired muscles and promotes relaxation. 500g jar.",
    image: "https://images.unsplash.com/photo-1600580642893-94a39ce6bf31?w=400&h=400&fit=crop",
    category: "Bath & Body",
    price: "$21.99",
    cardSize: "small",
  },
  {
    id: 16,
    name: "Woven Storage Basket",
    description: "Hand-woven storage basket from natural seagrass. Sturdy handles for easy carrying. Perfect for blankets, toys, or laundry.",
    image: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=400&h=400&fit=crop",
    category: "Home",
    price: "$42.99",
    cardSize: "medium",
  },
  {
    id: 17,
    name: "Copper Mug Set",
    description: "Set of 4 handcrafted copper mugs. Perfect for Moscow Mules or any cold beverage. Food-safe lining. Tarnish-resistant finish.",
    image: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400&h=400&fit=crop",
    category: "Kitchen",
    price: "$59.99",
    cardSize: "small",
  },
  {
    id: 18,
    name: "Dried Flower Arrangement",
    description: "Beautiful preserved flower arrangement in neutral tones. Long-lasting beauty without maintenance. Comes in glass vase.",
    image: "https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400&h=400&fit=crop",
    category: "Home",
    price: "$48.99",
    cardSize: "large",
  },
  {
    id: 19,
    name: "Hand-knit Wool Scarf",
    description: "Cozy hand-knit scarf from 100% merino wool. Soft against skin. Classic design in versatile neutral color.",
    image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop",
    category: "Accessories",
    price: "$79.99",
    cardSize: "medium",
  },
  {
    id: 20,
    name: "Wooden Cutting Board",
    description: "Premium end-grain cutting board from walnut and maple. Knife-friendly surface. Juice groove on one side. Heavy-duty construction.",
    image: "https://images.unsplash.com/photo-1594385208974-2e75f8d7bb48?w=400&h=400&fit=crop",
    category: "Kitchen",
    price: "$89.99",
    cardSize: "large",
  },
];

export function getProductById(id: number): Product | undefined {
  return products.find((p) => p.id === id);
}
